#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : memshrinker
Version  : 3
Release  : 11
URL      : http://localhost/cgit/projects/memshrinker/snapshot/memshrinker-3.tar.gz
Source0  : http://localhost/cgit/projects/memshrinker/snapshot/memshrinker-3.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: memshrinker-bin
Requires: memshrinker-config
Requires: memshrinker-autostart
BuildRequires : pkgconfig(check)
BuildRequires : pkgconfig(libsystemd)
BuildRequires : valgrind

%description
No detailed description available

%package autostart
Summary: autostart components for the memshrinker package.
Group: Default

%description autostart
autostart components for the memshrinker package.


%package bin
Summary: bin components for the memshrinker package.
Group: Binaries
Requires: memshrinker-config

%description bin
bin components for the memshrinker package.


%package config
Summary: config components for the memshrinker package.
Group: Default

%description config
config components for the memshrinker package.


%prep
%setup -q -n memshrinker-3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1510693377
export CFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
export FFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
%autogen --disable-static
make V=1  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1510693377
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files autostart
%defattr(-,root,root,-)
/usr/lib/systemd/system/multi-user.target.wants/memshrinker.service

%files bin
%defattr(-,root,root,-)
/usr/bin/memshrinker

%files config
%defattr(-,root,root,-)
%exclude /usr/lib/systemd/system/multi-user.target.wants/memshrinker.service
/usr/lib/systemd/system/memshrinker.service
